apiVersion: v1
kind: Namespace
metadata:
  name: team3-namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  namespace: team3-namespace
  labels:
    app: flask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: team3-flaskapp
        image: team3/flaskapp
        ports:
        - containerPort: 5000
        imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: team3-namespace
spec:
  selector:
    app: flask
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
